spring.application.name=backend-cible
server.port=8080

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:cible_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Logging
logging.level.web=DEBUG
logging.level.com.cible.backend_cible=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE