spring.application.name=backend-cible
server.port=8080
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.web=DEBUG
logging.level.be.he2b=DEBUG
logging.level.org.hibernate.SQL=TRACE

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:cible_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA/Hibernate - critical sort
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# allows to charge data.sql after the creation of tables
spring.jpa.defer-datasource-initialization=true