services:
  postgres:
    image: postgres:15
    container_name: pg-dev
    environment:
      POSTGRES_DB: CibleDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend-cible
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # Connexion à PostgreSQL via le service "postgres"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/CibleDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

volumes:
  pgdata: